FROM tsl0922/ttyd AS base

FROM paoloose/elenadb:latest

COPY --from=base /usr/bin/ttyd /usr/bin/ttyd

CMD ["ttyd", "-t", "fontSize=24", "-t", "theme={\"background\": \"black\"}", "--writable", "./elena", "demo/demo.db"]
