FROM tsl0922/ttyd AS base

FROM elenadb:latest

COPY --from=base /usr/bin/ttyd /usr/bin/ttyd

CMD ["ttyd", "-t", "titleFixed=\"ElenaDB shell\"", "-t", "fontSize=22", "-t", "theme={\"background\":\"black\",\"foreground\":\"#c5c8c6\",\"cursorAccent\":\"#1a1b26\",\"selectionBackground\":\"#28344a\",\"selectionForeground\":\"#7aa2f7\",\"black\":\"#414868\",\"red\":\"#f7768e\",\"green\":\"#73daca\",\"yellow\":\"#e0af68\",\"blue\":\"#7aa2f7\",\"magenta\":\"#bb9af7\",\"cyan\":\"#7dcfff\",\"white\":\"#fff\",\"brightBlack\":\"#414868\",\"brightRed\":\"#f7768e\",\"brightGreen\":\"#73daca\",\"brightYellow\":\"#e0af68\",\"brightBlue\":\"#7aa2f7\",\"brightMagenta\":\"#bb9af7\",\"brightCyan\":\"#7dcfff\",\"brightWhite\":\"#c0caf5\"}", "--writable", "./elena", "demo/demo.db"]
